// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_test_task

import (
	"fmt"
	"io"
	"strconv"
)

type Rate struct {
	// внутренний ИД задачи по которой будет осуществляться изменение состояния объекта в БД
	Currency Currency `json:"currency"`
	// текстовое описание задачи
	ExchangeRate float64 `json:"exchangeRate"`
}

type RateInput struct {
	Currency     Currency `json:"currency"`
	ExchangeRate float64  `json:"exchangeRate"`
}

type Currency string

const (
	CurrencyUsd Currency = "USD"
	CurrencyEur Currency = "EUR"
)

var AllCurrency = []Currency{
	CurrencyUsd,
	CurrencyEur,
}

func (e Currency) IsValid() bool {
	switch e {
	case CurrencyUsd, CurrencyEur:
		return true
	}
	return false
}

func (e Currency) String() string {
	return string(e)
}

func (e *Currency) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Currency(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Currency", str)
	}
	return nil
}

func (e Currency) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
